name 'oauth_proxy'
maintainer 'pyama86'
maintainer_email 'www.kazu.com@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures oauth-proxy-cookbook'
long_description 'Installs/Configures oauth-proxy-cookbook'
version '0.1.0'
chef_version '>= 13.0'
depends 'systemd'
